---
Name: fio-hidden-pages
---

SilverStripe\CMS\Model\SiteTree:
  hide_pagetypes:
    - SilverStripe\CMS\Model\VirtualPage

SilverStripe\CMS\Model\VirtualPage:
  extensions:
    fioHiddenPage: Fromholdio\HiddenPages\Extensions\HiddenPageExtension
